### PR TITLE
Properly set the c++ standard based on ROOT configuration

### PR DESCRIPTION
**Pull request by mfasDa**
Adaptions in the cmake file (CMakeLists.txt, cmake/FindRoot.cmake)
taken from AliPhysics cmake files.

### CODE REVIEW

**Comment by mfasDa** [comment]
@dberzano @ktf could you please check if this can be merged?

**Comment by dberzano** [comment]
Wouldn't it be better to make a PR to the upstream repo instead of patching our own? I see it difficult to maintain for the future.

**Comment by mfasDa** [comment]
@dberzano This commit is needed in order to compile RooUnfold when ROOT is compiled using c++14/17 (i.e. with the o2 defaults) - not sure you want to merge this anyway. Otherwise RooUnfold will not compile because it is not aware of the c++17 standard used in ROOT and will fail for std::string_view. If you insist we can try with the maintainers of the original repository whether this can be merged, but it might be faster to merge first in the ALICE fork.

Otherwise o2 defaults could use my fork with the V02-00-01-patches.

**Comment by dberzano** [comment]
Hi @mfasDa, there is no plan to move Run 2 software to anything further than C++11. Though I understand the rationale, I still recommend to propose the patch upstream and put some pressure there - my original comment was in January after all 😄

**Comment by dberzano** [comment]
...that said I agree that we can override RooUnfold only in O2 defaults. See [here](https://alice.its.cern.ch/jira/browse/ALIROOT-8072), I'll take care of it for the next AliRoot release.

**Comment by mfasDa** [comment]
Hi Dario,

OK, I opened a PR for the base repo - let's see if it get accepted. See https://github.com/kreczko/RooUnfold/pull/13.  In case not could you please merge the PR to this fork?

Cheers

Markus

**Pull request merged**
